/* Show Modals */
export const SET_CREATE_NEW_CLIENT_MODAL_STATUS = "SET_CREATE_NEW_CLIENT_MODAL_STATUS";
export const SET_EDIT_CLIENT_MODAL_STATUS = "SET_EDIT_CLIENT_MODAL_STATUS";
export const SET_SELECTED_USER_DETAILS = "SET_SELECTED_USER_DETAILS";
export const CLEAR_SELECTED_USER_DETAILS = "CLEAR_SELECTED_USER_DETAILS";

export const ADD_VENUE_DATA = "ADD_VENUE_DATA";
export const SET_SELECTED_VENUE_DATA = "SET_SELECTED_VENUE_DATA";
export const LOADING_VENUE_DATA = "LOADING_VENUE_DATA";
export const SET_VENUE_CANCEL_TOKEN = "SET_VENUE_CANCEL_TOKEN";
export const SET_VENUE_HAS_NO_MORE = "SET_VENUE_HAS_NO_MORE";
export const SET_FILTER_TYPE = "SET_FILTER_TYPE";
export const SET_SELECTED_VENUE_ID = "SET_SELECTED_VENUE_ID";
export const SET_FUNCTION_DATE_INFO = "SET_FUNCTION_DATE_INFO";

